"use client";
import { useEffect, useRef, useState } from "react";
type Candidate={id:string;canonicalEntityId:string;confidence:number;method:string;evidence:unknown};
type Decision={id:string;action:string;actor:string;evidence:unknown;canonicalEntityId:string|null;decidedAt:string;supersedesDecisionId?:string};
type ReviewCase={id:string;version:number;provider:string;externalId:string;incomingSnapshot:unknown;openedAt:string;candidates:Candidate[];decisions:Decision[]};
type Suggestion={provider:"THESPORTSDB";capturedAt:string;externalId:string;name:string;aliases:string[];logoRef:string|null};
export default function Page(){const[items,setItems]=useState<ReviewCase[]|null>(null),[failure,setFailure]=useState(false);const load=async()=>{try{const r=await fetch("/internal-api/reconciliation",{cache:"no-store"});if(!r.ok)throw 0;setItems((await r.json()).items)}catch{setFailure(true)}};useEffect(()=>{void load()},[]);return <section aria-labelledby="review-heading"><h1 id="review-heading">Ambiguity review queue</h1>{failure?<p role="alert">Review cases could not be loaded. No decision was changed. <button onClick={()=>{setFailure(false);void load()}}>Try again</button></p>:items===null?<p role="status">Loading review cases</p>:items.length===0?<h2>No ambiguity cases need review</h2>:<Workspace initialCase={items[0]!} reload={load}/>}</section>}
function Workspace({initialCase,reload}:{initialCase:ReviewCase;reload:()=>Promise<void>}){const[c,setCase]=useState(initialCase),[selected,setSelected]=useState(""),[note,setNote]=useState(""),[manual,setManual]=useState(""),[name,setName]=useState(""),[country,setCountry]=useState(""),[pending,setPending]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[confirming,setConfirming]=useState(false),[suggestions,setSuggestions]=useState<Suggestion[]|null>(null),[suggestionError,setSuggestionError]=useState(false);const reloadRef=useRef<HTMLButtonElement>(null);const loadSuggestions=async()=>{setSuggestionError(false);setSuggestions(null);try{const r=await fetch(`/internal-api/reconciliation/${encodeURIComponent(c.id)}/suggestions`,{cache:"no-store"});if(!r.ok)throw 0;setSuggestions((await r.json()).items)}catch{setSuggestionError(true)}};useEffect(()=>{void loadSuggestions()},[c.id]);useEffect(()=>{if(error.includes("case changed"))reloadRef.current?.focus()},[error]);const submit=async(kind:string,extra:Record<string,unknown>)=>{if(note.trim().length<10){setError("Evidence note must contain at least 10 non-whitespace characters.");return}setPending(true);setError("");setMessage("");try{const r=await fetch(`/internal-api/reconciliation/${encodeURIComponent(c.id)}/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,expectedVersion:c.version,idempotencyKey:crypto.randomUUID(),note,...extra})});if(r.status===409){setError("This case changed while you were reviewing it. Reload the latest decision before continuing.");queueMicrotask(()=>reloadRef.current?.focus());return}if(!r.ok)throw 0;const x=await r.json();setCase(v=>({...v,version:x.version,decisions:[...v.decisions,x.decision]}));setMessage("Decision recorded")}catch{setError("Decision could not be saved. No decision was changed. Try again.")}finally{setPending(false);setConfirming(false)}};return <div style={{display:"grid",gridTemplateColumns:"minmax(0, 1fr)",gap:24,overflowWrap:"anywhere"}}>
<section><h2>Case {c.externalId}</h2><dl><dt>Provider</dt><dd>{c.provider}</dd><dt>Opened</dt><dd>{new Date(c.openedAt).toISOString()}</dd></dl><details><summary>Raw provider snapshot</summary><pre style={{overflow:"auto",maxHeight:240,maxWidth:"100%"}}>{JSON.stringify(c.incomingSnapshot,null,2)}</pre></details></section>
<section><h3>Candidates</h3><fieldset><legend>Select a canonical match</legend>{c.candidates.map(x=><label key={x.id} style={{display:"block",minHeight:48}}><input type="radio" name="candidate" checked={selected===x.id} onChange={()=>setSelected(x.id)}/> {x.canonicalEntityId} — {Math.round(x.confidence*100)}% ({x.method})<pre>{JSON.stringify(x.evidence)}</pre></label>)}</fieldset></section>
<Suggestions items={suggestions} failed={suggestionError} retry={loadSuggestions} useName={setName}/>
<section><h3>Record decision</h3><p role="alert">{error}</p><p role="status">{message}</p><label>Evidence note<textarea value={note} onChange={e=>setNote(e.target.value)} disabled={pending}/></label><div><button disabled={pending||!selected} onClick={()=>void submit("approve",{candidateId:selected})}>{pending?"Saving decision…":"Approve selected match"}</button></div><label>Manual canonical entity ID<input value={manual} onChange={e=>setManual(e.target.value)}/></label><button disabled={pending||!manual} onClick={()=>void submit("manual-link",{canonicalEntityId:manual})}>Link manually</button><label>New canonical name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Country code<input value={country} onChange={e=>setCountry(e.target.value)}/></label><button disabled={pending||!name||!country} onClick={()=>setConfirming(true)}>Reject all and create canonical</button>{confirming&&<div role="dialog" aria-modal="true"><h4>Create canonical entity</h4><p>Create a new canonical entity? This may affect future reconciliation. The original evidence and this decision will remain in the audit history.</p><p>{JSON.stringify(c.incomingSnapshot)}</p><button onClick={()=>void submit("reject-create",{canonicalName:name,countryCode:country})}>Create canonical entity</button><button onClick={()=>setConfirming(false)}>Cancel</button></div>}<button ref={reloadRef} hidden={!error.includes("case changed")} onClick={()=>void reload()}>Reload case</button></section>
<section><h3>Audit history</h3>{c.decisions.length===0?<p>No prior decisions.</p>:<ol>{c.decisions.map(d=><li key={d.id}>{d.action} by {d.actor} at {d.decidedAt}; target {d.canonicalEntityId??"none"}; evidence {JSON.stringify(d.evidence)}{d.supersedesDecisionId?`; supersedes ${d.supersedesDecisionId}`:""}<button disabled={pending} onClick={()=>void submit("correction",{canonicalEntityId:manual||d.canonicalEntityId,supersedesDecisionId:d.id})}>Correct decision</button></li>)}</ol>}</section></div>}
function Suggestions({items,failed,retry,useName}:{items:Suggestion[]|null;failed:boolean;retry:()=>Promise<void>;useName:(x:string)=>void}){return <section><h3>TheSportsDB suggestions</h3><p>Names, aliases, and logos in this panel are review aids only. They are not production match evidence and cannot approve or change canonical identity.</p>{failed?<p role="alert">Suggestions could not be loaded. The reconciliation case and decisions were not changed. <button onClick={()=>void retry()}>Try loading suggestions again</button></p>:items===null?<p role="status">Loading suggestions</p>:items.length===0?<p>No suggestions found.</p>:<fieldset><legend>Suggestion review inputs</legend>{items.map(x=><div key={`${x.provider}:${x.externalId}`}><strong>{x.name??"Unnamed suggestion"}</strong><p>{(x.aliases??[]).join(", ")||"No aliases"}</p><small>{x.provider} · captured {x.capturedAt}</small>{x.logoRef?<img src={`/internal-api/provider-logo/${encodeURIComponent(x.logoRef)}`} alt={`${x.name} candidate logo`} referrerPolicy="no-referrer"/>:<p>Logo unavailable</p>}{x.name&&<button type="button" onClick={()=>useName(x.name)}>Use as review input</button>}</div>)}</fieldset>}</section>}
