"use client";

import { type KeyboardEvent, useEffect, useRef, useState } from "react";

type PrivacyStatus = { status: "OFF" | "ON" | "UNAVAILABLE"; reason?: string; policyVersion?: string; effectiveAt?: string; categories?: readonly string[] };
const panel = { border: "1px solid var(--border, #CBD5E1)", borderRadius: 10, background: "#FFFFFF", padding: 24, display: "grid", gap: 16 } as const;
const control = { minHeight: 48, padding: "8px 16px" } as const;

export default function PrivacyPage() {
  const [status, setStatus] = useState<PrivacyStatus | null>(null), [pending, setPending] = useState(false), [confirming, setConfirming] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState(false);
  const withdrawalTrigger = useRef<HTMLButtonElement>(null), dialogHeading = useRef<HTMLHeadingElement>(null), successHeading = useRef<HTMLHeadingElement>(null), errorAlert = useRef<HTMLParagraphElement>(null), confirmButton = useRef<HTMLButtonElement>(null), cancelButton = useRef<HTMLButtonElement>(null);
  const load = async () => { const response = await fetch("/internal-api/privacy/status", { cache: "no-store" }); setStatus(response.ok ? await response.json() as PrivacyStatus : { status: "UNAVAILABLE", reason: "STATUS_UNAVAILABLE" }); };
  useEffect(() => { void load(); }, []); useEffect(() => { if (confirming) dialogHeading.current?.focus(); }, [confirming]); useEffect(() => { if (success) successHeading.current?.focus(); }, [success]);
  const optIn = async () => { setPending(true); setError(""); try { const response = await fetch("/internal-api/privacy/consent", { method: "POST", headers: { "content-type": "application/json" }, body: "{}", cache: "no-store" }); if (!response.ok) throw new Error(); await load(); } catch { setError("Consent could not be saved. History retention remains off."); } finally { setPending(false); } };
  const close = () => { setConfirming(false); queueMicrotask(() => withdrawalTrigger.current?.focus()); };
  const withdraw = async () => { setPending(true); setError(""); setSuccess(false); try { const response = await fetch("/internal-api/privacy/withdrawal", { method: "POST", headers: { "content-type": "application/json" }, body: "{}", cache: "no-store" }); const payload = await response.json() as { correlationId?: string }; if (!response.ok) throw new Error(payload.correlationId ?? "Not available"); setConfirming(false); setSuccess(true); await load(); } catch (failure) { setConfirming(false); setError(`History deletion did not complete. Nothing was reported as deleted. Correlation ID: ${failure instanceof Error ? failure.message : "Not available"}.`); queueMicrotask(() => errorAlert.current?.focus()); } finally { setPending(false); } };
  const dialogKeys = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key === "Escape") { event.preventDefault(); close(); return; } if (event.key !== "Tab") return; const first = confirmButton.current, last = cancelButton.current; if (!first || !last) return; if (event.shiftKey && (document.activeElement === first || document.activeElement === dialogHeading.current)) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  const unavailable = status?.status === "UNAVAILABLE";
  return <section style={{ display: "grid", gap: 24, maxWidth: 760 }}><header><h1>Privacy and retained history</h1><p>Manual odds and analysis work without retaining personal history.</p></header><section aria-labelledby="retention-heading" style={panel} aria-busy={status === null || pending}><h2 id="retention-heading">{status === null ? "Loading history retention…" : status.status === "ON" ? "History retention is on" : status.status === "OFF" ? "History retention is off" : "History retention is unavailable"}</h2>{unavailable && <p>History retention is unavailable until the retention policy is complete</p>}<dl><dt>Policy version</dt><dd>{status?.policyVersion ?? "Not available"}</dd><dt>Effective date</dt><dd>{status?.effectiveAt ?? "Not available"}</dd><dt>Covered data</dt><dd>Submitted manual-odds history and viewed-result history</dd><dt>Excluded data</dt><dd>Immutable model receipts and non-personal system facts may remain only when they cannot be linked to you.</dd></dl><p>Optional. Manual odds and analysis still work when history retention is off.</p>{status?.status !== "ON" && <label><input type="checkbox" disabled={pending || unavailable} checked={false} onChange={() => void optIn()} /> Allow retention of my betting-related history under policy {status?.policyVersion ?? "Not available"}</label>}{status?.status === "ON" && <button ref={withdrawalTrigger} style={control} disabled={pending} onClick={() => setConfirming(true)}>Withdraw consent and delete history</button>}<a href="/methodology#responsible-use">Read the full privacy explanation</a><p role="status" aria-live="polite">{pending ? confirming ? "Deleting retained history…" : "Updating consent…" : ""}</p></section>{error && <p ref={errorAlert} role="alert" tabIndex={-1}>{error}</p>}{success && <section role="status" style={panel}><h2 ref={successHeading} tabIndex={-1}>Consent withdrawn</h2><p>Consent withdrawn. Retained betting history was deleted and future retention is off.</p></section>}{confirming && <div role="dialog" aria-modal="true" aria-labelledby="withdrawal-heading" style={panel} onKeyDown={dialogKeys}><h2 ref={dialogHeading} tabIndex={-1} id="withdrawal-heading">Delete retained betting history?</h2><p>This permanently deletes your retained odds and viewed-result history and stops future retention. Anonymous model receipts may remain only when they cannot be linked to you. This cannot be undone.</p><button ref={confirmButton} style={control} disabled={pending} onClick={() => void withdraw()}>{pending ? "Deleting history…" : "Delete history and withdraw consent"}</button><button ref={cancelButton} style={control} disabled={pending} onClick={close}>Keep consent</button></div>}</section>;
}
